//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Final.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NomUsager {
            get {
                return ((string)(this["NomUsager"]));
            }
            set {
                this["NomUsager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MotDePasse {
            get {
                return ((string)(this["MotDePasse"]));
            }
            set {
                this["MotDePasse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_Connexion_Pref {
            get {
                return ((bool)(this["DLG_Connexion_Pref"]));
            }
            set {
                this["DLG_Connexion_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_Connexion_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_Connexion_Taille"]));
            }
            set {
                this["DLG_Connexion_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_Connexion_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_Connexion_Position"]));
            }
            set {
                this["DLG_Connexion_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainForm_Taille {
            get {
                return ((global::System.Drawing.Size)(this["MainForm_Taille"]));
            }
            set {
                this["MainForm_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainForm_Position {
            get {
                return ((global::System.Drawing.Point)(this["MainForm_Position"]));
            }
            set {
                this["MainForm_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainForm_Pref {
            get {
                return ((bool)(this["MainForm_Pref"]));
            }
            set {
                this["MainForm_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_AjoutModif_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_AjoutModif_Taille"]));
            }
            set {
                this["DLG_AjoutModif_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_AjoutModif_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_AjoutModif_Position"]));
            }
            set {
                this["DLG_AjoutModif_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_AjoutModif_Pref {
            get {
                return ((bool)(this["DLG_AjoutModif_Pref"]));
            }
            set {
                this["DLG_AjoutModif_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_AjoutMonuments_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_AjoutMonuments_Taille"]));
            }
            set {
                this["DLG_AjoutMonuments_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_AjoutMonuments_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_AjoutMonuments_Position"]));
            }
            set {
                this["DLG_AjoutMonuments_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_AjoutMonuments_Pref {
            get {
                return ((bool)(this["DLG_AjoutMonuments_Pref"]));
            }
            set {
                this["DLG_AjoutMonuments_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_GererMonuments_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_GererMonuments_Taille"]));
            }
            set {
                this["DLG_GererMonuments_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_GererMonuments_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_GererMonuments_Position"]));
            }
            set {
                this["DLG_GererMonuments_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_GererMonuments_Pref {
            get {
                return ((bool)(this["DLG_GererMonuments_Pref"]));
            }
            set {
                this["DLG_GererMonuments_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_InfoMonument_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_InfoMonument_Taille"]));
            }
            set {
                this["DLG_InfoMonument_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_InfoMonument_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_InfoMonument_Position"]));
            }
            set {
                this["DLG_InfoMonument_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_InfoMonument_Pref {
            get {
                return ((bool)(this["DLG_InfoMonument_Pref"]));
            }
            set {
                this["DLG_InfoMonument_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_ListeMonuments_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_ListeMonuments_Taille"]));
            }
            set {
                this["DLG_ListeMonuments_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_ListeMonuments_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_ListeMonuments_Position"]));
            }
            set {
                this["DLG_ListeMonuments_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_ListeMonuments_Pref {
            get {
                return ((bool)(this["DLG_ListeMonuments_Pref"]));
            }
            set {
                this["DLG_ListeMonuments_Pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size DLG_Aide_Taille {
            get {
                return ((global::System.Drawing.Size)(this["DLG_Aide_Taille"]));
            }
            set {
                this["DLG_Aide_Taille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DLG_Aide_Position {
            get {
                return ((global::System.Drawing.Point)(this["DLG_Aide_Position"]));
            }
            set {
                this["DLG_Aide_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DLG_Aide_Pref {
            get {
                return ((bool)(this["DLG_Aide_Pref"]));
            }
            set {
                this["DLG_Aide_Pref"] = value;
            }
        }
    }
}
